sonar.projectKey=Space2Study-UA-4282-4286-team-01_Client-mvp
sonar.organization=space2study-ua-4282-4286-team-01

sonar.projectName=Client-mvp

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.exclusions=**/src/tests/**/*, **/build-story/*, **/node_modules/**
sonar.coverage.exclusions=**/src/constants/*, **/src/tests/**/*, **/*.styles.ts

sonar.tests=./src/tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude test subdirectories from source scope
sonar.javascript.lcov.reportPaths=./src/tests/coverage/lcov.info
sonar.testExecutionReportPaths=./test-report.xml
